// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgrmdyeiauiilbrkoucf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impncm1keWVpYXVpaWxicmtvdWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMTEyNTQsImV4cCI6MjA2NTg4NzI1NH0.HHmkYuWF8dzN0wUxxe6G9FxLqw3zNK4uFwHSEqf589g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);